### ISSUE TITLE
Design my organizer TODO list

### ISSUE THREAD

**Issue by paska27** [paska27/my-organizer#13]
- [x] item functionality: resolve, undo, cancel, delete from list
- [x] nesting
- [x] resolve parent when all children are resolved
- [x] resolve "branch" when ancestor is resolved 
- [x] reordering
- ~~label system~~ (#19)
- [x] reorder todos by labels

**Comment by paska27** [comment]
- [ ] item functionality: resolve, undo, cancel, delete from list
- [ ] nesting
- [ ] reordering
- [ ] resolve parent when all children are resolved
- [ ] resolve "branch" when ancestor is resolved
